apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "internal-app.fullname" . }}
  labels:
    {{- include "internal-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: {{ .Values.strategyType }}
  selector:
    matchLabels:
      {{- include "internal-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "internal-app.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
          - name: internal-app-storage
            persistentVolumeClaim:
              claimName: {{ include "internal-app.fullname" . }}-pvc
          - configMap:
              name: {{ include "internal-app.fullname" . }}-configmap
            name: configjson-volume
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.image }}
#          image: "{{- if .registry -}}{{ .registry }}/{{- end -}}{{ .repository }}{{- if (.digest) -}} @{{.digest}}{{- else -}}:{{ default $.Chart.AppVersion .tag }} {{- end -}}"
#          {{- end }}
#          image: "{{ .Values.image.imageRegistry }}:{{ .Values.image.dockerTag }}"          
#          image: "{{ .Values.image.imageRegistry }}"
          image: "{{ .Values.imageReg }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 4000
          env:
          - name: ConfigJsonPath
            value: /home/config.json 
          volumeMounts:
            - name: internal-app-storage
              mountPath: /mnt/fabric
            - name: configjson-volume
              mountPath: /home
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
