apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "internal-app.fullname" . }}-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.storage.app.storageclassname }}
  resources:
    requests:
      storage: {{ .Values.storage.app.storagesize }}
  selector:
    # To make sure we match the claim with the exact volume, match the label
    matchLabels:
      usage: {{ include "internal-app.fullname" . }}-pv
